[build]
  command = "npm install && npm run build"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  FAUNADB_SECRET = "your_faunadb_secret"
  CLOUDINARY_CLOUD_NAME = "your_cloudinary_cloud_name"
  CLOUDINARY_API_KEY = "your_cloudinary_api_key"
  CLOUDINARY_API_SECRET = "your_cloudinary_api_secret"